# Recommended method in https://matklad.github.io/2021/08/22/large-rust-workspaces.html
[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Tancr√®de Lepoint"]
documentation = "https://fhe.rs"
edition = "2021"
repository = "https://github.com/tlepoint/fhe.rs"
version = "0.1.0-beta.5"
license-file = "LICENSE"

[workspace.dependencies]
console = "0.15.7"
criterion = "0.5.1"
crypto-bigint = "0.5.3"
indicatif = "0.17.7"
itertools = "0.11.0"
ndarray = "0.15.6"
num-bigint = "0.4.4"
num-bigint-dig = "0.8.4"
num-traits = "0.2.16"
proptest = "1.3.1"
protobuf = "3.3.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
thiserror = "1.0.49"
zeroize = "1.6.0"
zeroize_derive = "1.4.2"
