# Recommended method in https://matklad.github.io/2021/08/22/large-rust-workspaces.html
[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["Tancr√®de Lepoint"]
documentation = "https://fhe.rs"
edition = "2021"
repository = "https://github.com/tlepoint/fhe.rs"
version = "0.1.0-beta.4"
license-file = "LICENSE"

[workspace.dependencies]
console = "0.15.2"
criterion = "0.4.0"
crypto-bigint = "0.4.9"
indicatif = "0.17.2"
itertools = "0.10.5"
ndarray = "0.15.6"
num-bigint = "0.4.3"
num-bigint-dig = "0.8.1"
num-traits = "0.2.15"
proptest = "1.0.0"
protobuf = "3.2.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = "0.10.6"
thiserror = "1.0.37"
zeroize = "1.5.7"
zeroize_derive = "1.3.3"
