[package]
name = "fhe"
description = "Fully Homomorphic Encryption in Rust"
version = "0.1.0-beta.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/tlepoint/fhe.rs"
homepage = "https://fhe.rs/"

[lib]
bench = false  # Disable default bench (we use criterion)

[dependencies]
fhe-math = { version = "^0.1.0-beta.1", path = "../fhe-math" }
fhe-traits = { version = "^0.1.0-beta.0", path = "../fhe-traits" }
fhe-util = { version = "^0.1.0-beta.0", path = "../fhe-util" }

itertools = "0.10.3"
num-bigint = "0.4.3"
num-traits = "0.2.15"
rand = "0.8.5"
rand_chacha = "0.3.1"
zeroize = "1.5.7"
zeroize_derive = "1.3.2"
ndarray = "0.15.6"
protobuf = "3.1.0"
thiserror = "1.0.34"

[dev-dependencies]
criterion = "0.3.6"
indicatif = "0.17.0"
itertools = "0.10.3"
ndarray = "0.15.6"
rand = "0.8.5"
console = "0.15.1"

[[bench]]
name = "bfv"
harness = false

[[bench]]
name = "bfv_optimized_ops"
harness = false

[[bench]]
name = "bfv_rgsw"
harness = false

[[example]]
name = "mulpir"

[[example]]
name = "sealpir"

[[example]]
name = "util"
